baseURL = 'http://simonjensen.net/'
languageCode = 'en-us'
title = "It's a website"
theme = 'moly'

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
